import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { UserProvider } from "@/context/userContext";

import { CurrentUserProvider } from "@/lib/currentUserContext";
import { ToastContainer } from "react-toastify";
import { SidebarProvider } from "@/context/sidebarContext";
// Configure fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PineBank",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="light" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CurrentUserProvider>
            <UserProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
              >
                <SidebarProvider>{children}</SidebarProvider>
                <ToastContainer />
              </ThemeProvider>
            </UserProvider>
          </CurrentUserProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
